# bpmai_lastrev_caise-negative_sampling-bce
job.type: train

dataset.name: bpmai_lastrev_caise

# training settings (fixed)
train:
  max_epochs: 400
  auto_correct: True
  batch_size: 512
  type: negative_sampling
  loss: bce
  optimizer: Adagrad
  optimizer_args.lr: 0.432197
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args.mode: max
  lr_scheduler_args.factor: 0.95
  lr_scheduler_args.threshold: 0.0001
  lr_scheduler_args.patience: 5

# validation/evaluation settings (fixed)
valid:
  every: 5
  metric: mean_reciprocal_rank_tail #_filtered_with_test
  filter_with_test: False
  early_stopping:
    patience: 10
    min_threshold.epochs: 50
    min_threshold.metric_value: 0.05

eval:
  batch_size: 256

entity_ranking:
  hits_at_k_s: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 50, 100, 1000]
  metrics_per:
    argument_frequency: False
    head_and_tail: True
    relation_type: False

# settings for reciprocal relations (if used)
import: [transe, reciprocal_relations_model]
reciprocal_relations_model.base_model.type: transe
model: reciprocal_relations_model

lookup_embedder:
  dim: 64
  initialize: xavier_normal_
  initialize_args.normal_.mean: 0.0
  initialize_args.normal_.std: 0.003318
  initialize_args.xavier_normal_.gain: 1.0
  regularize: 'l3'
  regularize_args.weighted: True 
  

transe:
  entity_embedder.regularize_weight: 0.015705
  relation_embedder.regularize_weight: 0.000699
  entity_embedder.dropout: 0.085233
  relation_embedder.dropout: 0.115673
  l_norm: 1.0
  entity_embedder.normalize.p: -1.0
  relation_embedder.normalize.p: 2.0

negative_sampling:
  num_negatives_s: 438
  num_negatives_o: 322 