# bpmai_lastrev_caise2-relationalTucker-KvsAll-kl
job.type: train

dataset.name: bpmai_lastrev_caise2

# training settings (fixed)
train:
  max_epochs: 400
  auto_correct: True
  type: KvsAll #KvsAll 1vsAll negative_sampling
  loss: kl #kl bce margin_ranking
  loss_arg: .nan
  optimizer.default.type: Adam
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 1
    threshold: 0.0001
  batch_size: 1024
  optimizer_args.lr: 0.001886
    
# validation/evaluation settings (fixed)
valid:
  every: 5
  metric: mean_reciprocal_rank_tail #_filtered_with_test
  filter_with_test: False
  early_stopping:
    patience: 10
    min_threshold.epochs: 50
    min_threshold.metric_value: 0.05

eval:
  batch_size: 256

entity_ranking:
  hits_at_k_s: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 50, 100, 1000]
  metrics_per:
    argument_frequency: False
    head_and_tail: True
    relation_type: False

import:
- reciprocal_relations_model
- relational_tucker3

model: reciprocal_relations_model

reciprocal_relations_model:
  base_model:
    entity_embedder:
      dim: 16
    relation_embedder:
      dim: -1
      base_embedder:
        type: lookup_embedder
    type: relational_tucker3

relational_tucker3:
  relation_embedder:
    regularize_args:
        weighted: True
  entity_embedder.regularize_weight: 0.000026
  relation_embedder.regularize_weight: 8.239337e-13	
  relational_tucker3.entity_embedder.dropout: 0.034014	
  relation_embedder.dropout: -0.394949	
    
lookup_embedder:
  initialize: xavier_normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.000423	
    xavier_normal_:
      gain: 1.0
  dim: 16
  regularize: ''
  regularize_args.weighted: True 

KvsAll:
  label_smoothing: 0.071816	