# bpmai_lastrev_caise2-negative_sampling-bce
job.type: train

dataset.name: bpmai_lastrev_caise2

# training settings (fixed)
train:
  max_epochs: 400
  auto_correct: True
  batch_size: 1024
  type: negative_sampling
  loss: bce
  optimizer: Adagrad
  optimizer_args.lr: 0.294312
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args.mode: max
  lr_scheduler_args.factor: 0.95
  lr_scheduler_args.threshold: 0.0001
  lr_scheduler_args.patience: 8

# validation/evaluation settings (fixed)
valid:
  every: 5
  metric: mean_reciprocal_rank_tail #_filtered_with_test
  filter_with_test: False
  early_stopping:
    patience: 10
    min_threshold.epochs: 50
    min_threshold.metric_value: 0.05

eval:
  batch_size: 256

entity_ranking:
  hits_at_k_s: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 50, 100, 1000]
  metrics_per:
    argument_frequency: False
    head_and_tail: True
    relation_type: False

# settings for reciprocal relations (if used)
import: [transe, reciprocal_relations_model]
reciprocal_relations_model.base_model.type: transe
model: reciprocal_relations_model

lookup_embedder:
  dim: 256
  initialize: uniform_
  initialize_args.uniform_.a: -0.493631
  initialize_args.xavier_uniform_.gain: 1.0
  regularize: 'l3'
  regularize_args.weighted: False 

transe:
  entity_embedder.regularize_weight: 5.053926e-20
  relation_embedder.regularize_weight: 0.056329
  entity_embedder.dropout: 0.376427
  relation_embedder.dropout: -0.426064
  l_norm: 2.0
  entity_embedder.normalize.p: -1.0
  relation_embedder.normalize.p: -1.0

negative_sampling:
  num_negatives_s: 2
  num_negatives_o: 81